name: house_cleaning
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  fl_chart: ^0.69.0
  flutter_svg: ^2.0.10+1
  flutter_rating: ^2.0.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  flutter_rating_bar: ^4.0.1
  the_apple_sign_in: ^1.1.1
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.2
  image_picker: ^1.1.2
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.1.0
  flutter_local_notifications: ^17.2.1+2
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  flutter_localization: ^0.2.2
  intl_utils: ^2.8.7
  intl: ^0.19.0
  flutter_facebook_auth: ^4.0.1

  shimmer: ^3.0.0

  http: ^1.2.2
  firebase_messaging: ^15.1.3
  googleapis_auth: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
