// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNG-HjyJGcuiMnFWytLm2jMJmMl-_Y3jY',
    appId: '1:1003248471502:web:a4fc59975792867a2e6f9f',
    messagingSenderId: '1003248471502',
    projectId: 'housecleaning-ed9da',
    authDomain: 'housecleaning-ed9da.firebaseapp.com',
    storageBucket: 'housecleaning-ed9da.appspot.com',
    measurementId: 'G-FCWZ72P8NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhTgApDD9WT_pNzLBwH1DR7-G0iWC-y1w',
    appId: '1:1003248471502:android:995c34f2deedc2c02e6f9f',
    messagingSenderId: '1003248471502',
    projectId: 'housecleaning-ed9da',
    storageBucket: 'housecleaning-ed9da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcVZzzHrIIutWpURe1iEhXraW21y4WJrs',
    appId: '1:1003248471502:ios:ebd0db93ec1cb0922e6f9f',
    messagingSenderId: '1003248471502',
    projectId: 'housecleaning-ed9da',
    storageBucket: 'housecleaning-ed9da.appspot.com',
    iosBundleId: 'com.aseef.houseCleaning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcVZzzHrIIutWpURe1iEhXraW21y4WJrs',
    appId: '1:1003248471502:ios:ebd0db93ec1cb0922e6f9f',
    messagingSenderId: '1003248471502',
    projectId: 'housecleaning-ed9da',
    storageBucket: 'housecleaning-ed9da.appspot.com',
    iosBundleId: 'com.aseef.houseCleaning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNG-HjyJGcuiMnFWytLm2jMJmMl-_Y3jY',
    appId: '1:1003248471502:web:6e07272129a007822e6f9f',
    messagingSenderId: '1003248471502',
    projectId: 'housecleaning-ed9da',
    authDomain: 'housecleaning-ed9da.firebaseapp.com',
    storageBucket: 'housecleaning-ed9da.appspot.com',
    measurementId: 'G-V98WTDM7BQ',
  );
}
