// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX1NCAH4ooUd2hpI2jUVflRVmJRKC8kVg',
    appId: '1:550265053132:web:c04eb58b7db1046ff98769',
    messagingSenderId: '550265053132',
    projectId: 'housecleaning-b5862',
    authDomain: 'housecleaning-b5862.firebaseapp.com',
    storageBucket: 'housecleaning-b5862.appspot.com',
    measurementId: 'G-GTD4NMZ5RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA-WUrH_uu7umE-vystBjT_o8p4N-a5sE',
    appId: '1:550265053132:android:a737e3588239cc00f98769',
    messagingSenderId: '550265053132',
    projectId: 'housecleaning-b5862',
    storageBucket: 'housecleaning-b5862.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDourYxD2K8D0PjgSpwG8YWQOt4dYXlPIw',
    appId: '1:550265053132:ios:7b0f62c89268f92ef98769',
    messagingSenderId: '550265053132',
    projectId: 'housecleaning-b5862',
    storageBucket: 'housecleaning-b5862.appspot.com',
    iosBundleId: 'com.aseef.houseCleaning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDourYxD2K8D0PjgSpwG8YWQOt4dYXlPIw',
    appId: '1:550265053132:ios:7b0f62c89268f92ef98769',
    messagingSenderId: '550265053132',
    projectId: 'housecleaning-b5862',
    storageBucket: 'housecleaning-b5862.appspot.com',
    iosBundleId: 'com.aseef.houseCleaning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX1NCAH4ooUd2hpI2jUVflRVmJRKC8kVg',
    appId: '1:550265053132:web:8a8ed291092be808f98769',
    messagingSenderId: '550265053132',
    projectId: 'housecleaning-b5862',
    authDomain: 'housecleaning-b5862.firebaseapp.com',
    storageBucket: 'housecleaning-b5862.appspot.com',
    measurementId: 'G-ZNEMX3JKRN',
  );

}