// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAqdq5SansakgmJp1aRDEF6KSfDb_c7ss',
    appId: '1:68453052702:web:b25bdce4dab713b432990f',
    messagingSenderId: '68453052702',
    projectId: 'housecleaning-9286f',
    authDomain: 'housecleaning-9286f.firebaseapp.com',
    storageBucket: 'housecleaning-9286f.appspot.com',
    measurementId: 'G-MPXG4BBFDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdJGf8ZuQDLDf8ISgcnEn6wQpVtgb-sIA',
    appId: '1:68453052702:android:46d033d1863784df32990f',
    messagingSenderId: '68453052702',
    projectId: 'housecleaning-9286f',
    storageBucket: 'housecleaning-9286f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWk1k4KYyCDoo3Ncp9tS7FbHxqCteFBdk',
    appId: '1:68453052702:ios:c0ba90bb8ec580c032990f',
    messagingSenderId: '68453052702',
    projectId: 'housecleaning-9286f',
    storageBucket: 'housecleaning-9286f.appspot.com',
    iosBundleId: 'com.aseef.houseCleaning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWk1k4KYyCDoo3Ncp9tS7FbHxqCteFBdk',
    appId: '1:68453052702:ios:c0ba90bb8ec580c032990f',
    messagingSenderId: '68453052702',
    projectId: 'housecleaning-9286f',
    storageBucket: 'housecleaning-9286f.appspot.com',
    iosBundleId: 'com.aseef.houseCleaning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAqdq5SansakgmJp1aRDEF6KSfDb_c7ss',
    appId: '1:68453052702:web:feeaf77c72e1fa9932990f',
    messagingSenderId: '68453052702',
    projectId: 'housecleaning-9286f',
    authDomain: 'housecleaning-9286f.firebaseapp.com',
    storageBucket: 'housecleaning-9286f.appspot.com',
    measurementId: 'G-MDQHZH98HD',
  );
}
